talent-factory/TalentFactory/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from TalentFactory import settings

urlpatterns = [

    path('', include("home.urls")),
    path("cars/", include("car.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

talent-factory/car/urls.py
from django.urls import path

from car.views import CarsListView, CarDetailView, CarsCreateView, CarsDeleteView

urlpatterns = [
    
    path("", CarsListView.as_view(), name="cars-list"),
    path("register/", CarsCreateView.as_view(), name="cars-create"),
    path("<str:book_id>/detail/", CarDetailView.as_view(), name="cars-detail"),
    path("<str:book_id>/", CarsDeleteView.as_view(), name="cars-delete")
]

talent-factory/home/urls.py
from django.urls import path
from home.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home' )
]

talent-factory/car/models.py
from django.db import models
import uuid



class Car(models.Model):

    GENRES_TYPE_CHOICES = (
    ('NONE', 'GENEROS'),
    ('Religious', 'RELIGIOSO'),
    ('Tales', 'CONTOS'),
    ('Affairs', 'ROMANCE'),
    ('Comedy', 'COMÉDIA')
)


    book_id = models.UUIDField(
        primary_key=True,
        auto_created=True,
        default=str(uuid.uuid4())
    )
    
    book_year = models.IntegerField()
    description = models.TextField(max_length=1024)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    photo_car = models.ImageField(upload_to="photos/")

    def to_dict(self):
        return {
            "book_id": str(self.car_id),
            "book_year": self.car_year,
            "description": self.description,
            "price": self.price,
            "photo_car": self.photo_car
        }

    def __str__(self):
        return f"book: {self.book_id}"

talent-factory/home/models.py
from django.db import models

# Create your models here.

talent-factory/car/forms.py
from django import forms

from car.models import Car 



class CarForms(forms.ModelForm):
    GENRES_TYPE_CHOICES = (
    ('NONE', 'GENEROS'),
    ('Religious', 'RELIGIOSO'),
    ('Tales', 'CONTOS'),
    ('Affairs', 'ROMANCE'),
    ('Comedy', 'COMÉDIA')
)

    book_id = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'bg-app-gray-400 rounded-none px-3 placeholder:font-semibold placeholder:font-roboto '
                        'placeholder:text-app-blue-300 py-1 placeholder:text-sm hidden',
                'placeholder': 'INPUT THE BOOK',
                'readonly': True
            }
        )
    )

    book_year = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'class': 'bg-app-gray-400 rounded-none px-3 placeholder:font-semibold placeholder:font-roboto '
                        'placeholder:text-app-blue-300 py-1 placeholder:text-sm',
                'placeholder': 'INPUT THE BOOK YEAR'
            }
        )
    )

    price = forms.DecimalField(
        widget=forms.NumberInput(
            attrs={
                'class': 'bg-app-gray-400 rounded-none px-3 placeholder:font-semibold placeholder:font-roboto '
                        'placeholder:text-app-blue-300 py-1 placeholder:text-sm',
                'placeholder': 'INPUT THE BOOK PRICE'
            }
        )
    )

    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'bg-app-gray-400 rounded-none px-3 placeholder:font-semibold placeholder:font-roboto '
                        'placeholder:text-app-blue-300 py-2 placeholder:text-sm w-full h-36',
                'placeholder': 'DESCRIBE THE MAIN INFORMATION ABOUT THE BOOK'
            }
        )
    )


    photo_car = forms.ImageField()

    class Meta:
        model = Car
        fields = "__all__"

        def __init__(self, detail: bool =False, *args, **kwargs):
            super(CarForms, self).__init__(*args, **kwargs)

            for _, field in self.fields.items():
                

                if detail:
                    field.widget.attrs["disable"] = True

                    

talent-factory/car/views.py
from uuid import uuid4
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import View
from car.filters import CarFilter 
from car.forms import CarForms 
from car.models import Car 


class CarsListView(View):
    def get(self, request):
        filter_form = CarFilter(request.GET, request=request)

        return render(request, "cars/list.html", {
            "extraHeadContext": {
                "title": "Cars List"
            },
            "context": {
                "situation": request.GET.get("situation"),
                "titleOfPage": request.GET.get("situation", "").upper(),
                "filter": filter_form
            }
        })

class CarsCreateView(View):
    def post(self, request):
        create_form = CarForms(request.POST, request.FILES)
        if create_form.is_valid():
            create_form.save()

            return redirect(
                f"{reverse('cars-list')}?situation={request.POST.get('situation')}"
            )
        print(create_form.errors)
        return render(request, "cars/forms.html", {
            "extraHeadContext": {
                "title": "Cars Create"
            },
            "context": {
                "situation": request.GET.get("situation"),
                "titleOfPage": request.GET.get("situation", "").upper(),
                "form": create_form
            }
        })

    def get(self, request):
        create_form = CarForms(
            initial={
                "book_id": str(uuid4())
            }
        )

        return render(request, "cars/forms.html", {
            "extraHeadContext": {
                "title": "Cars Create"
            },
            "context": {
                "situation": request.GET.get("situation"),
                "titleOfPage": request.GET.get("situation", "").upper(),
                "form": create_form
            }
        })

class CarsDeleteView(View):
    def get(self, request, book_id):
        car = Car.objects.filter(book_id=book_id)
        car.delete()

        return redirect(
            f"{reverse('cars-list')}?situation={request.GET.get('situation')}"
        )

class CarDetailView(View):
    def get(self, request, book_id):
        car = get_object_or_404(Car, book_id=book_id)
        detail_form = CarForms(detail=True, initial=car.to_dict())

        return render(request, "cars/form.html", {
            "extraHeadContext": {
                "title": "Cars Detail"
            },
            "context": {
                "situation": request.GET.get("situation"),
                "titleOfPage": car.situation.upper(),
                "mode": 'detail',
                "form": detail_form
            }
        })

talent-factory/home/views.py
from django.shortcuts import render
from django.views.generic import View # CBV


class HomeView(View):
    def get(self, request):
        return render(
            request,
            template_name="home.html",
            context={
                "extraContext":{
                    "title": "home"
                }
            }
        )

talent-factory/car/templates/cars/forms.html
{% extends 'base.html' %}
{% load static %}

{% block extraHead %}
    <link rel="stylesheet" href="{% static 'css/filter-form.css' %}">
    <script src="{% static 'js/file-input-control.js' %}"></script>
    <script src="{% static 'js/checkbox-control.js' %}"></script>
{% endblock extraHead %}

{% block mainContent %}
    <div class="w-screen h-[calc(100vh-84px)] pt-8 p-12 space-y-4 pb-10">
        <h1 class="text-blue-500 text-2xl font-bold">
            {% if context.mode != 'detail' %}
                REGISTER THE BOOK
            {% else %}
                DETAIL OF THE BOOK <span class="px-10 ml-6 py-1 text-xl bg-gray-400 rounded-full text-red-500 font-bold">{{ context.form.situation.value|upper }} CAR</span>
            {% endif %}
        </h1>
        <form action="{% url 'cars-create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ context.form.book_id }}
            <div class="flex items-center gap-4">
                <div class="flex items-center gap-2">
                    <input readonly type="checkbox" name="situation_aux" id="new">
                    <label for="new" class="flex">NEW</label>
                </div>
                <div class="flex items-center gap-2">
                    <input readonly type="checkbox" name="situation_aux" id="pre-made">
                    <label for="pre-made" class="flex">PRE-MADE</label>
                </div>
                <div class="flex items-center gap-2">
                    <input readonly type="checkbox" name="situation_aux" id="promotional">
                    <label for="promotional" class="flex">PROMOTIONAL</label>
                </div>
            </div>
            <div class="grid grid-cols-2 gap-x-40 mt-4">
                <div class="flex flex-col gap-y-6">
                   
                    {{ context.form.book_year }}
                    <div class="hidden">{{ context.form.book_id }}</div>
                    {{ context.form.description }}
                    {{ context.form.price }}


                </div>
                <div class="flex flex-col gap-y-6">
                    <div class="row-span-3 w-full">
                        
                    </div>
                    {% if context.mode == 'detail' %}
                        <div id="file-container" class="row-span-5 w-full mb-auto">
                            <img class="w-96 h-52" src="{{ context.form.photo_car.value.url }}" alt="">
                        </div>
                        <div class="grid grid-cols-2">

                        </div>
                    {% else %}
                        <div id="file-container" class="row-span-5 w-full mb-auto">
                            <label for="id_photo_car" class="cursor-pointer w-full flex font-bold text-gray-500 items-center px-3 py-1.5 gap-2">
                                <i class="bi bi-box-arrow-in-down text-app-blue-400"></i>
                                ATTACH THE BOOK'S PHOTO
                            </label>
                            <div class="hidden">
                                {{ context.form.photo_car }}
                            </div>
                        </div>
                        <div class="grid grid-cols-2">
                            
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="flex items-center justify-end gap-4">
                <a href="{% url 'cars-list' %}?situation={{ context.situation }}" class="px-4 py-2 rounded-none font-bold text-white bg-red-500 text-sm">BACK</a>
                {% if context.mode != 'detail' %}
                    <button type="submit" class="px-4 py-2 rounded-none font-bold text-white bg-blue-500 text-sm">REGISTRAR</button>
                {% endif %}
            </div>
        </form>
    </div>
{% endblock mainContent %}

talent-factory/car/templates/cars/list.html
{% extends 'base.html' %}
{% load static %}

{% block extraHead %}
    <link rel="stylesheet" href="{% static 'css/filter-form.css' %}">
    <script src="{% static 'js/form-control.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
{% endblock extraHead %}

{% block mainContent %}
    <div class="w-screen h-[calc(100vh-84px)] pt-8 p-12 space-y-4 pb-10">
        <h1 class="text-blue-500 text-2xl font-bold">
            {% if context.situation == 'sell-your-car' %}
                BOOK FOR SELLING LIST
            {% else %}
                {{ context.titleOfPage }} BOOKS FOR SALE
            {% endif %}
        </h1>
        <form id="filter-form" class="flex items-center justify-between w-full">
            <div class="flex items-center gap-8">
                {{ context.filter.form.as_p }}
            </div>
            <div class="flex items-center gap-6">
                <a class="px-4 py-2 rounded-none font-bold text-white bg-red-500 text-sm">EXPORT</a>
                <a href="{% url 'cars-create' %}?situation={{ context.situation }}" class="px-4 py-2 rounded-none font-bold text-white bg-blue-500 text-sm">
                    + ADD NEW BOOK {% if context.situation == 'sell-your-car' %} TO SELL {% endif %}
                </a>
            </div>
        </form>
        {% if context.situation == 'sell-your-car' %}
            <div></div>
        {% else %}
            <div class="flex flex-wrap gap-10">
            {% for car in context.filter.qs %}
                <div  id="delete-modal-{{ car.book_id }}" class="blocker hidden">
                    <div class="modal p-4">
                      <div class="bg-gray-400 h-full flex items-center gap-8 justify-center flex-col">
                          <p class="text-blue-500 font-bold px-10">ARE YOU SURE YOU WANT TO DELETE THE FOLLOWING BOOK?</p>
                          <div class="flex items-center justify-center gap-8">
                              <button onclick="closeModal('{{ car.book_id }}')" class="w-32 py-1 bg-red-500 font-bold text-white">CANCEL</button>
                              <a href="{% url 'cars-delete' book_id=car.book_id %}?situation={{ context.situation }}" class="w-32 py-1 bg-blue-500 font-bold text-white">YES</a>
                          </div>
                      </div>
                    </div>
                </div>
            	<div class="flex flex-col justify-start items-start relative">
                    <button onclick="openDeleteModal('{{ car.book_id }}')" class="absolute top-[10px] right-[10px] text-red-900" rel="modal:open">
                        <i class="bi bi-trash-fill"></i>
                    </button>
                    <button onclick="window.location = '{% url 'cars-detail' book_id=car.book_id %}?situation={{ context.situation }}'">
                        <img class="w-52 h-80" src="{{ car.photo_car.url }}" alt="">
                        <div class="w-full text-center flex flex-col items-start mt-2">
                            <p class="text-center w-full font-roboto font-bold text-black text-ellipsis overflow-hidden">
                                {{ car.model|upper }}
                            </p>
                            <p class="text-center w-full font-roboto font-bold text-black text-ellipsis overflow-hidden"> 
                                
                            </p>
                            <p class="text-center w-full font-roboto font-bold text-black text-ellipsis overflow-hidden">
                                YEAR - {{ car.book_year }}  
                            </p>
                            <p class="text-center w-full font-roboto font-bold text-red-900 text-ellipsis overflow-hidden">
                                U$ {{ car.price }}
                            </p>
                        </div>
                    </button>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock mainContent %}

{% block extraJS %}
    <script>
        function openDeleteModal(carId) {
            $(`#delete-modal-${carId}`).fadeIn()
        }

        function closeModal(carId) {
            $(`#delete-modal-${carId}`).fadeOut()
        }
    </script>
{% endblock extraJS %}

talent-factory/home/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block extraHead %}
    <script src="{% static 'js/slider.js' %}"></script>
{% endblock extraHead %}

{% block mainContent %}
    <div class="w-screen h-[calc(100vh-84px)] py-10 relative">
        <button id="back" class="absolute -translate-y-1/2 top-1/2 left-4 bg-white rounded-full text-2xl size-8 flex items-center justify-center">
            <i class="bi bi-arrow-left-short"></i>
        </button>
        <div id="slider-container" class="w-screen h-full flex overflow-hidden">
            <div class="bg-cover h-full flex-[0_0_100%_!important] w-screen bg-[url({% static 'images/car_1.png' %})]"></div>
            <div class="bg-cover h-full flex-[0_0_100%_!important] w-screen bg-[url({% static 'images/car_2.png' %})]"></div>
            <div class="bg-cover h-full flex-[0_0_100%_!important] w-screen bg-[url({% static 'images/car_3.png' %})]"></div>
        </div>
        <button id="next" class="absolute -translate-y-1/2 top-1/2 right-4 bg-white rounded-full text-2xl size-8 flex items-center justify-center">
            <i class="bi bi-arrow-right-short"></i>
        </button>
    </div>
{% endblock mainContent %}

talent-factory/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
        <script src="https://unpkg.com/@phosphor-icons/web"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <script src="https://cdn.tailwindcss.com"></script>

        <script scr="{% static 'js/tailwind-config.js' %}"></script>


        {% if extraContext.title %}
            <title>{{extraContext.Title}} | BRSC Best Luxury Cars</title>
        {% else %}
            <title>BRSC Best Luxury Cars</title>
        {% endif %}
        {% block extraHead %}{% endblock extraHead %}
    </head>

    <body>
        {%  include 'fragments/navbar.html' %}
        {% block mainContent %}{% endblock mainContent %}
        {% block extraJS %}{% endblock extraJS %}
    </body>
</html>

talent-factory/templates/fragments/navbar.html
{% load static %}

{% block extraHead %}
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock extraHead %}

<nav class="navbar p-4 flex justify-between">
    <a href="{% url 'home' %}">
        <img src="{% static 'images/Group 1.png' %}" alt="Uma imagem com a logo da marca">
    </a>

    <div class="flex gap-3 items-center">
        <a class="border-b-2 bg-app-gray-400 {% if context.situation == 'new' %}border-b-black font-bold{% endif %}" id="new" href="{% url 'cars-list' %}?situation=new">
            BOOKS
        </a>
        <span class="mb-2">|</span>

        <a class="border-b-2 bg-app-gray-400 {% if context.situation == 'pre-made' %}border-b-black font-bold{% endif %}" id="pre-made" href="{% url 'cars-list' %}?situation=pre-made">
            AUTHORS
        </a>
        <span class="mb-2">|</span>

        <a class="border-b-2 bg-app-gray-400 {% if context.situation == 'promotional' %}border-b-black font-bold{% endif %}" id="promotional" href="{% url 'cars-list' %}?situation=promotional">
            PROMOTIONAL
        </a>
        <span class="mb-2">|</span>

        <a class="border-b-2 bg-app-gray-400 {% if context.situation == 'contact' %}border-b-black font-bold{% endif %}" id="contact" href="{% url 'cars-list' %}?situation=contact">
            CONTACT
        </a>
        <span class="mb-2">|</span>

    </div> 

    <div class="flex gap-2 items-center">
        <i class="bi bi-instagram text-blue-500"></i>
        <i class="bi bi-facebook text-blue-500"></i>
        <i class="bi bi-linkedin text-blue-500"></i>
        <i class="bi bi-whatsapp text-blue-500"></i>
    </div>
</nav>